//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClientWPF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFileTransfer")]
    public interface IFileTransfer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/ReceiveStream", ReplyAction="http://tempuri.org/IFileTransfer/ReceiveStreamResponse")]
        void ReceiveStream(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/ReceiveStream", ReplyAction="http://tempuri.org/IFileTransfer/ReceiveStreamResponse")]
        System.Threading.Tasks.Task ReceiveStreamAsync(System.IO.Stream stream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/SendStream", ReplyAction="http://tempuri.org/IFileTransfer/SendStreamResponse")]
        System.IO.Stream SendStream();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileTransfer/SendStream", ReplyAction="http://tempuri.org/IFileTransfer/SendStreamResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> SendStreamAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileTransferChannel : ChatClientWPF.ServiceReference1.IFileTransfer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileTransferClient : System.ServiceModel.ClientBase<ChatClientWPF.ServiceReference1.IFileTransfer>, ChatClientWPF.ServiceReference1.IFileTransfer {
        
        public FileTransferClient() {
        }
        
        public FileTransferClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileTransferClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransferClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileTransferClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ReceiveStream(System.IO.Stream stream) {
            base.Channel.ReceiveStream(stream);
        }
        
        public System.Threading.Tasks.Task ReceiveStreamAsync(System.IO.Stream stream) {
            return base.Channel.ReceiveStreamAsync(stream);
        }
        
        public System.IO.Stream SendStream() {
            return base.Channel.SendStream();
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> SendStreamAsync() {
            return base.Channel.SendStreamAsync();
        }
    }
}
